import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  SystemArchitectureSidebar: [
    {
      type: "autogenerated",
      dirName: "system-architecture",
    },
  ],
  AboutSidebar: [
    {
      type: "autogenerated",
      dirName: "about",
    },
  ],
  ContributingSidebar: [
    {
      type: "autogenerated",
      dirName: "contributing",
    },
  ],
  QueryingSidebar: [
    {
      type: "autogenerated",
      dirName: "access",
    },
  ],
  DataFormatReferenceSidebar: [
    {
      type: "autogenerated",
      dirName: "reference",
    },
  ],
  PlaygroundSidebar: [
    {
      type: "autogenerated",
      dirName: "playground",
    },
  ],
};

export default sidebars;
