# title: All rivers that have "Charles" in their name
# category: Location Queries
# tags: mainstem, pattern

PREFIX hyf: <https://www.opengis.net/def/schema/hy_features/hyf/>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?mainstem ?name ?wkt
WHERE {
  BIND("Charles" AS ?searchString)

  # flowpath allows us to filter by mainstems
  ?mainstem a hyf:HY_FlowPath ;
    schema:name ?name ;
    gsp:hasGeometry/gsp:asWKT ?wkt .

  # Case-insensitive substring match
  FILTER(CONTAINS(LCASE(STR(?name)), LCASE(STR(?searchString))))
}
ORDER BY ?name
