# title: All rivers that are upstream of the Sacramento River
# category: Location Queries
# tags: mainstem, downstream

PREFIX hyf: <https://www.opengis.net/def/schema/hy_features/hyf/>
PREFIX gsp: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT ?mainstems ?wkt
WHERE {
  VALUES ?mainstem { <https://geoconnex.us/ref/mainstems/1> }
  ?mainstems hyf:downstreamWaterbody+ ?mainstem ;
    gsp:hasGeometry/gsp:asWKT ?wkt .
}
